service: default
env: flex
runtime: python37

beta_settings:
      cloud_sql_instances: abiding-orb-278309:europe-west3:databasefleetboard

# 8080 port needs to match the port specified in the app.py
# app:server needs to match the app.py file and the server variable in the app.py
entrypoint: gunicorn -b 0.0.0.0:8080 app:server

