runtime: python
env: flex

entrypoint: uwsgi --socket 127.0.0.1:8080 --protocol=http --module main --callable app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
      cloud_sql_instances: abiding-orb-278309:europe-west3:databasefleetboard


