runtime: python
env: flex

entrypoint: gunicorn -b 0.0.0.0:8080 main:server

runtime_config:
  python_version: 3.7

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
      cloud_sql_instances: abiding-orb-278309:europe-west3:databasefleetboard=tcp:5432