runtime: python
env: flex

# 8080 port needs to match the port specified in the app.py
# app:server needs to match the app.py file and the server variable in the app.py
entrypoint: gunicorn -b 0.0.0.0:8080 app:server

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
      cloud_sql_instances: abiding-orb-278309:europe-west3:databasefleetboard


