service: default
runtime: python38

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10

# 8080 port needs to match the port specified in the app.py
# app:server needs to match the app.py file and the server variable in the app.py
entrypoint: gunicorn -b 0.0.0.0:8080 app:server

beta_settings:
      cloud_sql_instances: abiding-orb-278309:europe-west3:databasefleetboard
