runtime: python
env: flex

entrypoint: uwsgi --socket 34.107.92.36:8080 --protocol=http --module main --callable application

runtime_config:
  python_version: 37

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
      cloud_sql_instances: abiding-orb-278309:europe-west3:databasefleetboard


