import pandas as pd

# import NREL-Fleet-DNA-Data.csv as dataframe 'df'
df = pd.read_csv('Batch-data/composite-data-for-fleet-dna-csv-1.csv')

# create new dataframe with all relevant columns and add all the IDs and vehicle information
new = df[['vid', 'did', 'pid', 'class_id', 'voc_id', 'type_id', 'drive_id', 'fuel_id', 'day_id']].copy()

# add all relevant columns from category 'Speed' (original column 17-123, 287-372)
new['speed_data_duration_hrs'] = df['speed_data_duration_hrs'].copy()
new['driving_data_duration_hrs'] = df['driving_data_duration_hrs'].copy()
new['max_speed'] = df['max_speed'].copy()
new['total_average_speed'] = df['total_average_speed'].copy()
new['total_median_speed'] = df['total_median_speed'].copy()
new['driving_average_speed'] = df['driving_average_speed'].copy()
new['zero_seconds'] = df['zero_seconds'].copy()
new['zero_five_seconds'] = df['zero_five_seconds'].copy()
new['seventy_five_plus_seconds'] = df['seventy_five_plus_seconds'].copy()
new['driving_time_seconds'] = df['driving_time_seconds'].copy()
new['percent_zero'] = df['percent_zero'].copy()
new['percent_zero_five'] = df['percent_zero_five'].copy()
new['percent_distance_seventy_five_plus'] = df['percent_distance_seventy_five_plus'].copy()
new['distance_zero_five'] = df['distance_zero_five'].copy()
new['distance_seventy_five_plus'] = df['distance_seventy_five_plus'].copy()
new['aerodynamic_speed'] = df['aerodynamic_speed'].copy()
new['as_standard'] = df['as_standard'].copy()
new['group_ttl_mean_speed'] = df['group_ttl_mean_speed'].copy()
new['group_ttl_std_speed'] = df['group_ttl_std_speed'].copy()
new['group_ttl_zero_speed'] = df['group_ttl_zero_speed'].copy()
new['matched_ttl_mean_speed'] = df['matched_ttl_mean_speed'].copy()
new['matched_ttl_std_speed'] = df['matched_ttl_std_speed'].copy()
new['matched_ttl_zero_speed'] = df['matched_ttl_zero_speed'].copy()
new['non_matched_ttl_mean_speed'] = df['non_matched_ttl_mean_speed'].copy()
new['non_matched_ttl_std_speed'] = df['non_matched_ttl_std_speed'].copy()
new['non_matched_ttl_zero_speed'] = df['non_matched_ttl_zero_speed'].copy()
new['func_1_mean_speed'] = df['func_1_mean_speed'].copy()
new['func_1_std_speed'] = df['func_1_std_speed'].copy()
new['func_1_zero_speed'] = df['func_1_zero_speed'].copy()
new['func_2_mean_speed'] = df['func_2_mean_speed'].copy()
new['func_2_std_speed'] = df['func_2_std_speed'].copy()
new['func_2_zero_speed'] = df['func_2_zero_speed'].copy()
new['func_3_mean_speed'] = df['func_3_mean_speed'].copy()
new['func_3_std_speed'] = df['func_3_std_speed'].copy()
new['func_3_zero_speed'] = df['func_3_zero_speed'].copy()
new['func_4_mean_speed'] = df['func_4_mean_speed'].copy()
new['func_4_std_speed'] = df['func_4_std_speed'].copy()
new['func_4_zero_speed'] = df['func_4_zero_speed'].copy()
new['func_5_mean_speed'] = df['func_5_mean_speed'].copy()
new['func_5_std_speed'] = df['func_5_std_speed'].copy()
new['func_5_zero_speed'] = df['func_5_zero_speed'].copy()
new['spd_cat_1_mean_speed'] = df['spd_cat_1_mean_speed'].copy()
new['spd_cat_1_std_speed'] = df['spd_cat_1_std_speed'].copy()
new['spd_cat_1_ttl'] = df['spd_cat_1_ttl'].copy()
new['spd_cat_1_zero_speed'] = df['spd_cat_1_zero_speed'].copy()
new['spd_cat_2_mean_speed'] = df['spd_cat_2_mean_speed'].copy()
new['spd_cat_2_std_speed'] = df['spd_cat_2_std_speed'].copy()
new['spd_cat_2_ttl'] = df['spd_cat_2_ttl'].copy()
new['spd_cat_2_zero_speed'] = df['spd_cat_2_zero_speed'].copy()
new['spd_cat_3_mean_speed'] = df['spd_cat_3_mean_speed'].copy()
new['spd_cat_3_std_speed'] = df['spd_cat_3_std_speed'].copy()
new['spd_cat_3_ttl'] = df['spd_cat_3_ttl'].copy()
new['spd_cat_3_zero_speed'] = df['spd_cat_3_zero_speed'].copy()
new['spd_cat_4_mean_speed'] = df['spd_cat_4_mean_speed'].copy()
new['spd_cat_4_std_speed'] = df['spd_cat_4_std_speed'].copy()
new['spd_cat_4_ttl'] = df['spd_cat_4_ttl'].copy()
new['spd_cat_4_zero_speed'] = df['spd_cat_4_zero_speed'].copy()
new['spd_cat_5_mean_speed'] = df['spd_cat_5_mean_speed'].copy()
new['spd_cat_5_std_speed'] = df['spd_cat_5_std_speed'].copy()
new['spd_cat_5_ttl'] = df['spd_cat_5_ttl'].copy()
new['spd_cat_5_zero_speed'] = df['spd_cat_5_zero_speed'].copy()
new['spd_cat_6_mean_speed'] = df['spd_cat_6_mean_speed'].copy()
new['spd_cat_6_std_speed'] = df['spd_cat_6_std_speed'].copy()
new['spd_cat_6_ttl'] = df['spd_cat_6_ttl'].copy()
new['spd_cat_6_zero_speed'] = df['spd_cat_6_zero_speed'].copy()
new['spd_cat_7_mean_speed'] = df['spd_cat_7_mean_speed'].copy()
new['spd_cat_7_std_speed'] = df['spd_cat_7_std_speed'].copy()
new['spd_cat_7_ttl'] = df['spd_cat_7_ttl'].copy()
new['spd_cat_7_zero_speed'] = df['spd_cat_7_zero_speed'].copy()
new['spd_cat_8_mean_speed'] = df['spd_cat_8_mean_speed'].copy()
new['spd_cat_8_std_speed'] = df['spd_cat_8_std_speed'].copy()
new['spd_cat_8_ttl'] = df['spd_cat_8_ttl'].copy()
new['spd_cat_8_zero_speed'] = df['spd_cat_8_zero_speed'].copy()

# add all relevant columns from category 'Acceleration and Deceleration' (original column 124-173)
new['total_number_of_acceleration_events'] = df['total_number_of_acceleration_events'].copy()
new['total_number_of_deceleration_events'] = df['total_number_of_deceleration_events'].copy()
new['acceleration_events_per_mile'] = df['acceleration_events_per_mile'].copy()
new['deceleration_events_per_mile'] = df['deceleration_events_per_mile'].copy()
new['max_acceleration_ft_per_second_squared'] = df['max_acceleration_ft_per_second_squared'].copy()
new['max_deceleration_ft_per_second_squared'] = df['max_deceleration_ft_per_second_squared'].copy()
new['average_acceleration_ft_per_second_squared'] = df['average_acceleration_ft_per_second_squared'].copy()
new['average_deceleration_ft_per_second_squared'] = df['average_deceleration_ft_per_second_squared'].copy()
new['average_acceleration_event_duration'] = df['average_acceleration_event_duration'].copy()
new['average_deceleration_event_duration'] = df['average_deceleration_event_duration'].copy()
new['min_acceleration_event_duration'] = df['min_acceleration_event_duration'].copy()
new['min_deceleration_event_duration'] = df['min_deceleration_event_duration'].copy()
new['max_acceleration_event_duration'] = df['max_acceleration_event_duration'].copy()
new['max_deceleration_event_duration'] = df['max_deceleration_event_duration'].copy()
new['characteristic_acceleration'] = df['characteristic_acceleration'].copy()
new['characteristic_deceleration'] = df['characteristic_deceleration'].copy()
new['ca_standard'] = df['ca_standard'].copy()
new['cd_standard'] = df['cd_standard'].copy()
new['cumulative_acceleration_duration'] = df['cumulative_acceleration_duration'].copy()
new['cumulative_deceleration_duration'] = df['cumulative_deceleration_duration'].copy()
new['absolute_time_cumulative_acceleration_duration'] = df['absolute_time_cumulative_acceleration_duration'].copy()
new['absolute_time_cumulative_deceleration_duration'] = df['absolute_time_cumulative_deceleration_duration'].copy()


# add all relevant columns from category 'Stops' (original column 174-192)
new['average_stop_duration'] = df['average_stop_duration'].copy()
new['min_stop_duration'] = df['min_stop_duration'].copy()
new['max_stop_duration'] = df['max_stop_duration'].copy()
new['stops_0_30'] = df['stops_0_30'].copy()
new['stops_30_60'] = df['stops_30_60'].copy()
new['stops_60_plus'] = df['stops_60_plus'].copy()
new['stops_300_plus'] = df['stops_300_plus'].copy()
new['stops_1800_plus'] = df['stops_1800_plus'].copy()
new['stops_3600_plus'] = df['stops_3600_plus'].copy()
new['stops_per_mile'] = df['stops_per_mile'].copy()
new['total_stops'] = df['total_stops'].copy()

# add all relevant columns from category 'Elevation' (original column 193-232)
new['max_elevation'] = df['max_elevation'].copy()
new['min_elevation'] = df['min_elevation'].copy()
new['mean_elevation'] = df['mean_elevation'].copy()
new['delta_elevation'] = df['delta_elevation'].copy()
new['total_elevation_gained'] = df['total_elevation_gained'].copy()
new['total_elevation_lost'] = df['total_elevation_lost'].copy()
new['max_climbing_rate'] = df['max_climbing_rate'].copy()
new['average_climbing_rate'] = df['average_climbing_rate'].copy()
new['max_descending_rate'] = df['max_descending_rate'].copy()
new['average_descending_rate'] = df['average_descending_rate'].copy()

# add all relevant columns from category 'Power Density' (original column 234-292)

# add all relevant columns from category 'Road Data' (original column 294-272)

# save new df as new csv-file in same folder
new.to_csv('Batch-data/cleaned-data-for-fleet-dna.csv')